### ISSUE TITLE
Support for older cassandra versions

### ISSUE THREAD

**Issue by nilroy** [spotify/cassandra-reaper#126]
Does it work with cassandra 1.2.19? I tried building for cassandra 1.2.19 by changing the pom.xml file but there are many compilation errors

====
ERROR] /root/cassandra-reaper/src/main/java/com/spotify/reaper/core/RepairRun.java:[16,35] package org.apache.cassandra.repair does not exist
[ERROR] /root/cassandra-reaper/src/main/java/com/spotify/reaper/core/RepairRun.java:[40,17] cannot find symbol
  symbol:   class RepairParallelism
  location: class com.spotify.reaper.core.RepairRun
[ERROR] /root/cassandra-reaper/src/main/java/com/spotify/reaper/core/RepairRun.java:[111,10] cannot find symbol
  symbol:   class RepairParallelism
  location: class com.spotify.reaper.core.RepairRun
=====

**Comment by Bj0rnen** [comment]
Well, we never intended to support 1.2, and don't do officially. And as you see, Reaper doesn't compile with that dependency. But we have found Reaper compiled for 2.0 to work without a problem against 1.2 clusters anyway. So that's something you can at least give a try.
